### ISSUE TITLE
TODO: доработки velik_bot

### ISSUE THREAD

**Issue by Nakilon** [Nakilon/velik_bot#1]
- [ ] алиасы команд
- репа
  - [ ] облачная бд
  - [x] нечеткий поиск по репам
- [x] автоматический `\help`
- клипы
  - [x] `\lastclip`
  - [x] `\clip_from <канал> <запрос>`
- чатгпт
  - [x] заставить отвечать лаконичней
  - [x] `\ignore`
- гуны
  - [x] вырубить флуд
  - [x] пофиксить парсинг таймстампа
  - [ ] баг: не должен писать везде про гунов, когда дергают команду, а goons_regular_report = false
- [x] алиас "велик" к "velik_bot"
- [ ] чтобы отказывался слушаться пользователя, если он -реп боту накидал
